makelist.local gen_int_list.crl ppc -mlongcall
makelist.local vme_tir_timeinfo ppc -mlongcall
makelist.local vme_ts.crl ppc -mlongcall
makelist.local vme_tir.crl ppc -mlongcall
makelist.local vme_tir_latch.crl ppc -mlongcall
makelist.local vme_tir_tdc.crl ppc -mlongcall
makelist.local vme_tir_latch_tdc.crl  ppc -mlongcall
makelist.local vme_list2.crl ppc -mlongcall
makelist.local vme_tir_noCDO.crl ppc -mlongcall
makelist.local event_list.crl  ppc -mlongcall
