makelist.local ROC12.crl ppc -mlongcall
makelist.local ROC14.crl ppc -mlongcall
makelist.local ROC15.crl ppc -mlongcall
makelist.local ROC17.crl ppc -mlongcall
makelist.local ROC19.crl ppc -mlongcall
makelist.local ROC20.crl ppc -mlongcall
makelist.local ROC21.crl ppc -mlongcall
makelist.local ROC23.crl ppc -mlongcall
makelist.local ROC24.crl ppc -mlongcall
makelist.local ROC27.crl ppc -mlongcall
makelist.local ROC29.crl ppc -mlongcall
makelist.local ROC30.crl ppc -mlongcall
makelist.local ROC25_neo.crl ppc -mlongcall
makelist.local vme_ts_tir_scale.crl ppc -mlongcall
